# Generated by Django 2.2 on 2024-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(choices=[('commercial', 'Commercial'), ('house', 'House'), ('land', 'Land')], max_length=20)),
                ('facing', models.CharField(choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South')], max_length=10)),
                ('landmark', models.CharField(max_length=255)),
                ('land_area', models.CharField(max_length=100)),
                ('size_and_frontage', models.CharField(max_length=100)),
                ('property_class', models.CharField(choices=[('residential', 'Residential Area'), ('agriculture', 'Agriculture Land')], max_length=20)),
                ('number_of_owners', models.IntegerField()),
                ('sale_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease'), ('rent', 'Rent')], max_length=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
