# Generated by Django 4.2.16 on 2024-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_propertie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
